### ISSUE TITLE
KarteCrashReporting build failed while using carthage for xcframework

### ISSUE THREAD

**Issue by oMaxChen** [plaidev/karte-ios-sdk#12]
## Expected Behavior

`KarteCrashReporting` build success while using `carthage` for `xcframework`

## Current Behavior

`KarteCrashReporting` build failed while using `carthage` for `xcframework`

## Possible Solution

Skipping regular `carthage update` while using `karte-ios-sdk`, just using workarounds that carthage provided.

## Steps to Reproduce

1. add `github "plaidev/karte-ios-sdk"` to `Cartfile`
2. run `carthage update --use-xcframeworks`

## Context (Environment)

Trying to use `karte-ios-sdk` in Xcode 12 using `Carthage`.

MacOS 10.15.7
Xcode 12.4
Carthage 0.37.0
Karte: tried `Utilities-3.2.0`, `Utilities-3.3.0` and `master`

## Detailed Description

`KarteCrashReporting` is not supporting arm64 currently.

Build log as following:

`
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_KRTPLCrashReporter", referenced from:
      objc-class-ref in CrashReporting.o
  "_OBJC_CLASS_$_KRTPLCrashReporterConfig", referenced from:
      objc-class-ref in CrashReporting.o
  "_OBJC_CLASS_$_KRTPLCrashReport", referenced from:
      objc-class-ref in CrashReporting.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by tikidunpon** [comment]
Thanks for the report, I've shared it internally.

**Comment by tikidunpon** [comment]
@oMaxChen Hi, we've fixed this issue please update to KarteCrashReporting 2.4.0, thank you!

https://developers.karte.io/docs/release-notes-ios-sdk-v2#kartecrashreporting-240
