### ISSUE TITLE
Resolver in KarteUtilities fails when building with Xcode 12.5 and Swift 5.4

### ISSUE THREAD

**Issue by mt-maddim** [plaidev/karte-ios-sdk#14]
## Expected Behavior

App starts and Karte initializes properly.

## Current Behavior

The build finishes but when the app starts and calls `KarteApp.setup(appKey: [the key])` the process stops with the following error:

> RESOLVER: 'SelectorDetector:' not resolved. To disambiguate optionals use resover.optional().

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000112c54b50 in _swift_runtime_on_report ()
#1	0x0000000112ccee8c in _swift_stdlib_reportFatalErrorInFile ()
#2	0x00000001129668aa in _assertionFailure(_:_:file:line:flags:) ()
#3	0x000000010d540098 in Resolver.resolve<τ_0_0>(_:name:args:) at /Users/.../iOS/Pods/KarteUtilities/KarteUtilities/ThirdParty/Resolver/Resolver.swift:203
#4	0x000000010d53f8a5 in static Resolver.resolve<τ_0_0>(_:name:args:) at /Users/.../iOS/Pods/KarteUtilities/KarteUtilities/ThirdParty/Resolver/Resolver.swift:185
#5	0x000000010ccedadd in CoreService.hasValidSelector.getter at /Users/...
#6	0x000000010cceccbd in CoreService.isEnabled.getter at /Users/...
#7	0x000000010cd1ea86 in KarteApp.setup(configuration:) at /Users/...
#8	0x000000010cd1e99e in static KarteApp.setup(appKey:configuration:) at /Users/...
#9	0x000000010cd1f209 in @objc static KarteApp.setup(appKey:configuration:) ()
#10	0x000000010ccbc07c in KarteConfigurator.config() at /Users/...
#11	0x000000010ccbc1da in @objc KarteConfigurator.config() ()
#12	0x00007fff20363882 in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#13	0x00007fff20363851 in ___CFXRegistrationPost_block_invoke ()
#14	0x00007fff20362f81 in _CFXRegistrationPost ()
#15	0x00007fff203628ef in _CFXNotificationPost ()
#16	0x00007fff207e9027 in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#17	0x00007fff246bf4a5 in -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] ()
#18	0x00007fff246c4d63 in -[UIApplication _runWithMainScene:transitionContext:completion:] ()
#19	0x00007fff23ce629b in -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] ()
#20	0x00007fff24272726 in _UIScenePerformActionsWithLifecycleActionMask ()
#21	0x00007fff23ce6dad in __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke ()
#22	0x00007fff23ce686e in -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] ()
#23	0x00007fff23ce6bda in -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] ()
#24	0x00007fff23ce646f in -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] ()
#25	0x00007fff23cee6d8 in __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke ()
#26	0x00007fff2417c77d in +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] ()
#27	0x00007fff2428f60e in _UISceneSettingsDiffActionPerformChangesWithTransitionContext ()
#28	0x00007fff23cee3de in -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] ()
#29	0x00007fff23b117d5 in __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke ()
#30	0x00007fff23b1024e in -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] ()
#31	0x00007fff23b1140e in -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] ()
#32	0x00007fff246c3203 in -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] ()
#33	0x00007fff241a4ab4 in -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] ()
#34	0x00007fff25a1b40b in -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] ()
#35	0x00007fff25a43e55 in __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176 ()
#36	0x00007fff25a28f12 in -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] ()
#37	0x00007fff25a43b28 in __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke ()
#38	0x000000011359674e in _dispatch_client_callout ()
#39	0x0000000113599656 in _dispatch_block_invoke_direct ()
#40	0x00007fff25a695d0 in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#41	0x00007fff25a692b6 in -[FBSSerialQueue _targetQueue_performNextIfPossible] ()
#42	0x00007fff25a6977b in -[FBSSerialQueue _performNextFromRunLoopSource] ()
#43	0x00007fff20390ede in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#44	0x00007fff20390dd6 in __CFRunLoopDoSource0 ()
#45	0x00007fff2039029e in __CFRunLoopDoSources0 ()
#46	0x00007fff2038a9f7 in __CFRunLoopRun ()
#47	0x00007fff2038a1a7 in CFRunLoopRunSpecific ()
#48	0x00007fff2b874d85 in GSEventRunModal ()
#49	0x00007fff246c14df in -[UIApplication _run] ()
#50	0x00007fff246c639c in UIApplicationMain ()
#51	0x000000010cc84d73 in main at /Users/...
#52	0x00007fff2025abbd in start ()
```

This happens only on Xcode 12.5 and iOS 14.5. Runs without issue when building with Xcode 12.4.

## Steps to Reproduce

I have not yet tested in a simpler project but I believe building with Xcode 12.5/Swift 5.4 should reproduce.

## SDK Version

- KarteCore 2.14.1
- KarteInAppMessaging 2.8.1
- KarteRemoteNotification 2.4.0
- KarteUtilities 3.3.0

## iOS Version

iOS 14.5 is where the problem occurs. In 14.4 seems to be working fine.

## Build Environment

- macOS Version 11.2.3
- Xcode Version 12.5
- CocoaPods Version 1.10.1

## Context Details

Trying to upgrade our builds to the latest iOS (14.5)

## Logs

> RESOLVER: 'SelectorDetector:' not resolved. To disambiguate optionals use resover.optional().
> KarteUtilities/Resolver.swift:203: Fatal error
> 2021-05-17 17:03:10.266313+0900 [AppName][82651:1456293] KarteUtilities/Resolver.swift:203: Fatal error

**Comment by tikidunpon** [comment]
@mt-maddim 

Hi, thanks for the bug report.

Unfortunately I was not able to reproduce the issue with Xcode 12.5 / iOS 14.5 / Swift 5.4..

Could you please provide me with the following additional information?

- Does it happen on a real device / simulator? and what type of device is it?
- Does it happen every time? or occasionally? and what is the frequency?
- Is the [registerAllServices function](https://github.com/plaidev/karte-ios-sdk/blob/master/KarteCore/KarteApp.swift#L329) has called? 
- Can you share the Podfile and Podfile.lock?
- Can you share the minimum configuration project that causes the problem?

**Comment by mt-maddim** [comment]
@tikidunpon 
Thank you for the quick reply. I can give you the easy information for now. The rest might take some time as I have another priority running right now.

> What is the serial number of Xcode 12.5? I tried (12E262).

That is the version I am also trying on.

> Does it happen on a real device / simulator? and what type of device is it?

Haven't tested on a device yet, only the simulator.

> Does it happen every time? or occasionally? and what is the frequency?

Every time. The app launches and crashes at the splash screen (app and libs config stage)

> Is the registerAllServices function has called?

I need to confirm this. I will come back to you with this.

> Can you share the Podfile and Podfile.lock?

We are using SwiftPM for the app and the pod file is basically only your SDK. I will try to obfuscate it a bit once I get the chance and send it to you.
The lock file is this: 
```
PODS:
  - KarteCore (2.14.1):
    - KarteUtilities (~> 3.3)
  - KarteInAppMessaging (2.8.1):
    - KarteCore (~> 2.3)
    - KarteUtilities (~> 3.0)
  - KarteRemoteNotification (2.4.0):
    - KarteCore (~> 2.0)
    - KarteUtilities (~> 3.0)
  - KarteUtilities (3.3.0):
    - KarteUtilities/standard (= 3.3.0)
    - KarteUtilities/standard (3.3.0)
 
DEPENDENCIES:
  - KarteCore
  - KarteInAppMessaging
  - KarteRemoteNotification
 
SPEC REPOS:
  trunk:
    - KarteCore
    - KarteInAppMessaging
    - KarteRemoteNotification
    - KarteUtilities
 
SPEC CHECKSUMS:
  KarteCore: d09e56a55234202078e60b4d5c35362e6ee0f0c1
  KarteInAppMessaging: 5c05e89e52c6d2b7565cc9e3dc62844daf94912e
  KarteRemoteNotification: 6c3836cf3fe7679c876c4e377aa7b3ae9fa0d900
  KarteUtilities: 87d79d20649710937f9bfd4961d369bf77105152
 
PODFILE CHECKSUM: 23671513892f50dc114aebaf1d05e6ec150924f9
 
COCOAPODS: 1.10.1
```

> Can you share the minimum configuration project that causes the problem?

Unfortunately as I mentioned in the issue description I have not had the chance to test in a simple app and a minimum config version of the app in which the SDK is used is not possible as the app is quite complex with lots of modules. When/if we get down to such test I will let you know.

If this information cannot help and you cannot reproduce please give us some time to return to our attempt for the upgrade. We will let you know the results of that. 

Thank you.

**Comment by tikidunpon** [comment]
@mt-maddim 

Thank you for replying.

I tried following simulators but I has not reproduced.

- iPhone 8 Plus
- iPhone SE (2nd gen)
- iPhone 12 Pro Max
- iPad Pro (9.7-inch)

I would like the following information in addition to my earlier comment, thanks for your time.

I would like the following information in addition to my earlier comment.

- Deps of SwiftPM
- SDK Logs（You can use `KarteApp.setLogLevel(.verbose)` ）

Thanks for your time. I know you're busy.

**Comment by mt-maddim** [comment]
@tikidunpon 
Thank you for your time and sorry for the delay.

We went through more extensive tests. 

A fresh/simple project indeed had no trouble integrating.

We reintegrated the Pods in our project and still found the same issue.

We then tried the same thing with Carthage only to find that it was working fine.

At this point we can only guess that Cocoapods is doing something weird/different that Xcode 12.5 does not like in multi-module projects or Xcode 12.5 is doing something weird with the build phases. Carthage works for now so we will go with that.

As a side note. It would be awesome if you could start offering integration though SwiftPM. We know there is an [open issue](https://github.com/plaidev/karte-ios-sdk/issues/11) about that and we are looking forward to the release.

In any case, I believe we can consider this closed if there is nothing further from your side.

Thank you.

**Comment by tikidunpon** [comment]
@mt-maddim 
Thank you for taking the time to test this, and thank you for your request about SwiftPM integration.

We'll let you know if we learn anything about the CocoaPods issue.

Thank you.
