### ISSUE TITLE
Binary has different checksum to Package.swif

### ISSUE THREAD

**Issue by k-kohey** [plaidev/karte-ios-sdk#22]
## Expected Behavior

Binary has different checksum to Package.swift.

The checksum for KarteInAppMessaging defined in Package.swift is `a4c9bf7c72902d69801026bdc47351f21690b8c6168d29b2bc2d3f9babd46dc9`. However, the checksum of the actual downloaded KarteInAppMessaging.xcframework is `8b2409961caf98408dc0b08a63af9df78bfe2feed6c5a542ec12a6c6ed839e73`.
Therefore, the checksum should also be `8b2409961caf98408dc0b08a63af9df78bfe2feed6c5a542ec12a6c6ed839e73` in the definition in Package.swift.

## Current Behavior

Applications that depend on the karte-ios-sdk cannot be built because the karte-ios-sdk dependency cannot be resolved.
Attempting to resolve dependencies yields the following error

```
checksum of downloaded artifact of binary target 'KarteInAppMessaging' (8b2409961caf98408dc0b08a63af9df78bfe2feed6c5a542ec12a6c6ed839e73) does not match checksum specified by the manifest (a4c9bf7c72902d69801026bdc47351f21690b8c6168d29b2bc2d3f9babd46dc9)
```

## Steps to Reproduce

1. add karte-ios-sdk as a dependency
2. resolve dependencies of products added to dependencies in 1.

## SDK Version

2.14.0

## Build Environment

- macOS Version 13.5.2
- Xcode Version 15.2

**Comment by wasnot** [comment]
@k-kohey Thank you for reporting.

The problem was that there is a glitch in the release flow for SDK, which temporarily overwrote the existing version binary.

I have just deleted the overwritten version and reverted to the existing binary.
Could you try again?

We apologize for the inconvenience.

**Comment by k-kohey** [comment]
Successful resolution of dependence is now in place.
Thanks for the quick fix !
